version: "3.3"
services:

  consul:
    command: -server -bootstrap
    image: gliderlabs/consul-server
    ports:
      - "8300"
      - "8400"
      - "8500:8500"
      - "53"

  nginx:
    image: openlmis/nginx:5
    ports:
      - "${OL_HTTP_PORT:-80}:80"
    env_file: settings.env
    environment:
      NGINX_LOG_DIR: '/var/log/nginx/log'
    volumes:
      - 'nginx-log:/var/log/nginx/log'
      - 'consul-template-log:/var/log/consul-template'
    depends_on: [consul]

  reference-ui:
    image: openlmis/reference-ui:5.2.8-SNAPSHOT
    env_file: settings.env
    depends_on: [consul]

  requisition:
    image: openlmis/requisition:8.3.8-SNAPSHOT
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx1024m -Dlogging.config=/config/log/logback.xml'
    volumes:
      - 'service-config:/config'
    depends_on: [log, db]
    command: ["/wait-for-postgres.sh", "/run.sh"]

  referencedata:
    image: openlmis/referencedata:15.2.7-SNAPSHOT
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx1024m -Dlogging.config=/config/log/logback.xml'
    volumes:
      - 'service-config:/config'
    depends_on: [log, db]
    command: ["/wait-for-postgres.sh", "/run.sh"]

  auth:
    image: openlmis/auth:4.3.4-SNAPSHOT
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx512m -Dlogging.config=/config/log/logback.xml'
    volumes:
      - 'service-config:/config'
    depends_on: [log, db]
    command: ["/wait-for-postgres.sh", "/run.sh"]

  notification:
    image: openlmis/notification:4.3.4-SNAPSHOT
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx512m -Dlogging.config=/config/log/logback.xml'
    volumes:
      - 'service-config:/config'
    depends_on: [log, db]
    command: ["/wait-for-postgres.sh", "/run.sh"]

  fulfillment:
    image: openlmis/fulfillment:9.0.6-SNAPSHOT
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx512m -Dlogging.config=/config/log/logback.xml'
    volumes:
      - 'service-config:/config'
    depends_on: [log, db]
    command: ["/wait-for-postgres.sh", "/run.sh"]

  cce:
    image: openlmis/cce:1.3.3-SNAPSHOT
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx512m -Dlogging.config=/config/log/logback.xml'
    volumes:
      - 'service-config:/config'
    depends_on: [log, db]
    command: ["/wait-for-postgres.sh", "/run.sh"]

  stockmanagement:
    image: openlmis/stockmanagement:5.1.10-SNAPSHOT
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx512m -Dlogging.config=/config/log/logback.xml'
    volumes:
      - 'service-config:/config'
    depends_on: [log, db]
    command: ["/wait-for-postgres.sh", "/run.sh"]

  report:
    image: openlmis/report:1.2.3-SNAPSHOT
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx512m -Dlogging.config=/config/log/logback.xml'
    volumes:
      - 'service-config:/config'
    depends_on: [log, db]
    command: ["/wait-for-postgres.sh", "/run.sh"]

  buq:
    image: openlmis/buq:1.0.0-SNAPSHOT
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx1024m -Dlogging.config=/config/log/logback.xml'
    volumes:
      - 'service-config:/config'
    depends_on: [ log, db ]
    command: [ "/wait-for-postgres.sh", "/run.sh" ]

  hapifhir:
    restart: always
    image: openlmis/hapifhir:2.0.3-SNAPSHOT
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx512m -Dlogging.config=/config/log/logback.xml'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
    depends_on: [log, db]
    command: ["/wait-for-postgres.sh", "/run.sh"]
    
  diagnostics:
    image: openlmis/diagnostics:1.1.3-SNAPSHOT
    env_file: settings.env
    environment:
      JAVA_OPTS: '-server -Xmx512m -Dlogging.config=/config/log/logback.xml'
      spring_profiles_active: ${spring_profiles_active}
    volumes:
      - 'service-config:/config'
    depends_on: [log]

  db:
    image: openlmis/postgres:12-debezium
    env_file: settings.env
    networks:
      default:
        aliases:
          - olmis-db
    depends_on: [consul]

  log:
    image: openlmis/rsyslog:2
    volumes:
      - 'syslog:/var/log'
    depends_on:
      - service-configuration
      - consul

  service-configuration:
    build:
      context: ./config
    volumes:
      - service-config:/config

  ftp:
    image: hauptmedia/proftpd:latest
    ports:
      - "${OL_FTP_PORT_21:-21}:21"
      - "${OL_FTP_PORT_20:-20}:20"
    env_file: settings.env
    depends_on: [consul]

  redis:
    image: redis:3.2.12
    depends_on: [consul]

volumes:
  syslog:
    external: false
  nginx-log:
    external: false
  consul-template-log:
    external: false
  service-config:
    external: false
